# Generated by Django 3.2.5 on 2024-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='canceled_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_orders',
            field=models.IntegerField(default=0),
        ),
    ]
