# Generated by Django 3.2.5 on 2024-08-03 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 10, 43, 8, 212511, tzinfo=utc)),
        ),
    ]
